variable "organization" {}
variable "environment" {}
variable "cost_center_tag" {}
variable "scalr_environment_id" {}
variable "app_domain" {}
variable "auth_secret" {}
variable "django_secrets_encryption_key" {}
variable "django_token_signing_key" {}
variable "django_token_verifying_key" {}
variable "postgres_admin_password" {}
variable "postgres_password" {}
