repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.97.4
  hooks:
    - id: terraform_fmt
    - id: terraform_checkov
      args:
      - --args=--framework terraform
      - --args=--check HIGH,CRITICAL
      - --args=--quiet
      - --args=--compact
    - id: terraform_trivy
      args:
      - --args=--severity HIGH,CRITICAL
      - --args=--quiet
    - id: terraform_docs
      args:
        - --hook-config=--path-to-file=README.md        # Valid UNIX path. I.e. ../TFDOC.md or docs/README.md etc.
        - --hook-config=--add-to-existing-file=true     # Boolean. true or false
        - --hook-config=--create-file-if-not-exist=false # Boolean. true or false
          # The following two options "--custom-marker-begin" and "--custom-marker-end" are ignored if "--use-standard-markers" is set to false
        - --hook-config=--custom-marker-begin=<!-- BEGIN_TF_DOCS -->  # String.
                                                        # Set to use custom marker which helps you with using other formats like asciidoc.
                                                        # For Asciidoc this could be "--hook-config=--custom-marker-begin=// BEGIN_TF_DOCS"
        - --hook-config=--custom-marker-end=<!-- END_TF_DOCS -->  # String.
                                                        # Set to use custom marker which helps you with using other formats like asciidoc.
                                                        # For Asciidoc this could be "--hook-config=--custom-marker-end=// END_TF_DOCS"
        - --hook-config=--custom-doc-header="# "        # String. Defaults to "# "
                                                        # Set to use custom marker which helps you with using other formats like asciidoc.
                                                        # For Asciidoc this could be "--hook-config=--custom-marker-end=\= "
